<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-7EJ4QKC" name="preserveOrder.PriotyCheckingWithXMLandPriority" tests="5" failures="1" timestamp="2020-09-23T23:55:23 IST" time="0.026" errors="0">
  <testcase name="startApp" time="0.011" classname="preserveOrder.PriotyCheckingWithXMLandPriority">
    <failure type="java.lang.AssertionError" message="Force fully failling the  expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Force fully failling the  expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertTrue(Assert.java:43)
at preserveOrder.PriotyCheckingWithXMLandPriority.startApp(PriotyCheckingWithXMLandPriority.java:10)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- startApp -->
  <system-out/>
  <testcase name="startApa" time="0.000" classname="preserveOrder.PriotyCheckingWithXMLandPriority"/>
  <system-out/>
  <testcase name="alwaysrun" time="0.005" classname="preserveOrder.PriotyCheckingWithXMLandPriority"/>
  <system-out/>
  <testcase name="LoginIntoApp" time="0.000" classname="preserveOrder.PriotyCheckingWithXMLandPriority"/>
  <system-out/>
  <testcase name="LogoutFromApp" time="0.010" classname="preserveOrder.PriotyCheckingWithXMLandPriority"/>
  <system-out/>
</testsuite> <!-- preserveOrder.PriotyCheckingWithXMLandPriority -->
